---
- name: Deploy VC and Hosts
  hosts: localhost
  gather_facts: False
  roles:
    # Base vsphere section
    - role: vsphere/vsphere-deploy-vc-and-hosts
    - role: vsphere/vsphere-datacenter
    - role: vsphere/vsphere-clusters
    - role: vsphere/vsphere-vswitch0-port-groups
    - role: vsphere/vsphere-local-datastores
    - role: vsphere/vsphere-nfs-datastores
    - role: vsphere/vsphere-enable-cluster-services
    - role: vsphere/vsphere-resource-pools
    - role: vsphere/vsphere-distributed-switches
      when: 'distributed_switches is defined'
    - role: vsphere/vsphere-distributed-port-groups
      when: 'distributed_switches is defined'

    # NSX-T Section
    - role: nsxt/nsxt-manager
      when: 'nsxt is defined'
    - role: nsxt/nsxt-ip-pools
      when: 'nsxt is defined'
    - role: nsxt/nsxt-ip-blocks
      when: 'nsxt.ip_blocks is defined'
    - role: nsxt/nsxt-principal-identities
      when: 'nsxt.principal_identities is defined'
    - role: nsxt/nsxt-uplink-profiles
      when: 'nsxt is defined'
    - role: nsxt/nsxt-transport-zones
      when: 'nsxt is defined'
    - role: nsxt/nsxt-transport-nodes
      when: 'nsxt is defined'
    - role: nsxt/nsxt-edge-clusters
      when: 'nsxt is defined'
    - role: nsxt/nsxt-switching-routing
      when: 'nsxt is defined'

    # vSphere with Kubernetes Section
    - role: vsphere/vsphere-storage-based-policy-management
      when: 'tspbm is defined'
    - role: tkg-service/vsphere-content-library
      when: 'tkg_service is defined'
    - role: tkg-service/tkgs-vyos-router
      when: 'tkg_router is defined'
    - role: tkg-service/tkgs-ha-proxy
      when: 'tkg_haproxy is defined'
    - role: tkg-service/tkgs-enable-cluster
      when: 'tkg_service is defined'
     
    # Harbor section
    - role: harbor-standalone/harbor-vm
      when: 'harbor_standalone is defined'

# Separate section to run commands inside harbor VM if created
- name:  Setup Standalone Harbor
  hosts: harbor
  become: true
  roles:
    - role: harbor-standalone/harbor-configuration
      when: 'harbor_standalone is defined'

- name: Display Summary
  hosts: localhost
  gather_facts: False
  roles:
    ### Show outputs at the end
    - role: display-configuration
