---

- debug: msg="{{tkg_haproxy}}"

- name: Deploy HA Proxy
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ nested_vcenter.ip }}"
    username: "{{ nested_vcenter.username }}" 
    password: "{{ nested_vcenter.password }}" 
    validate_certs: no
    name: "tkg-haproxy"
    datacenter: "{{ nested_vcenter.datacenter }}"
    cluster: "{{ tkg_service.vsphere_cluster }}"
    datastore: "{{ tkg_haproxy.datastore }}"
    disk_provisioning: "{{ disk_mode }}"
    networks:  
      Management: "{{ tkg_service.management_port_group }}"
      Workload: "{{ tkg_service.vsphere_networking.workload_port_group }}"
      Frontend: "{{ tkg_service.vsphere_networking.workload_port_group }}"
    ova: "{{ lookup('env', 'SOFTWARE_DIR') }}/vmware-haproxy-v0.1.8.ova" 
    allow_duplicates: no
    power_on: yes
    fail_on_spec_warnings: yes
    wait: yes
    wait_for_ip_address: yes
    inject_ovf_env: yes
    properties:
      appliance.root_pwd: "{{ tkg_haproxy.root_pwd }}"
      network.nameservers: "{{ tkg_haproxy.nameservers }} "
      network.management_ip: "{{ tkg_haproxy.management_ip }}/{{ tkg_haproxy.management_subnet_bits }}"
      network.management_gateway: "{{ tkg_haproxy.management_gateway }}"
      network.workload_ip: "{{ tkg_haproxy.workload_ip }}"
      network.workload_gateway: "{{ tkg_haproxy.workload_gateway }}"
      loadbalance.service_ip_range: "{{ tkg_haproxy.service_ip_range }}"
      loadbalance.haproxy_user: "{{ tkg_haproxy.username }}"
      loadbalance.haproxy_pwd:  "{{ tkg_haproxy.password }}"
      loadbalance.dataplane_port: "{{ tkg_haproxy.management_port | default(omit) }}"